name: "Backend Update"

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKENDKEY }}

      - name: Save the SSH key
        run: echo "$AWS_SECRET_ACCESS_KEY" > backendKey.pem

      - name: Set permissions to use the key
        run: chmod 600 backendKey.pem

      - name: Set EC2 instance details
        run: |
          INSTANCE_ID=${{ secrets.INSTANCE_ID }}
          PUBLIC_IP=${{ secrets.PUBLIC_IP }}

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i backendKey.pem ubuntu@$PUBLIC_IP << 'EOF'
          set -e
          cd /home/ubuntu/DEVOPSSEC_CA1
          git pull origin master
          pkill -f "rails server" || true
          sudo apt-get update
          sudo apt-get install -y ruby-dev build-essential
          sudo bundle install && sudo bundle update
          rails db:migrate
          EOF

      - name: Clean up SSH key
        run: rm -f backendKey.pem
